# 异常处理存在的问题

## 1.不在业务代码层面考虑异常处理

不建议在框架层面进行异常的自动,统一处理,尤其不要随意捕获异常.但框架可以做兜底工作.如果异常上升到最商城逻辑还是无法处理的话,可以统一的方式进行异常转换,比如通过`@RestControllerAdvice`和`@ExceptionHandler`,来捕获这些未处理异常;

* 对于自定义的业务异常,以Warn级别的日志记录异常以及当前URL,执行方法等信息,提取异常中的错误码和消息等信息,转化为合适的API包装体返回给API调用方;
* 对于无法处理的系统异常,以Error级别的日志记录异常和上下文信息(比如URL,参数,用户ID)后,转换成"服务器忙,请稍后再试"异常信息,同样以API包装体返回给调用方;

~~~java
@RestControllerAdvice
@Slf4j
public class RestControllerExceptionHandler {
    private static int GENERIC_SERVER_ERROR_CODE = 2000;
    private static String GENERIC_SERVER_ERROR_MESSAGE = "服务器忙，请稍后再试";

    @ExceptionHandler
    public APIResponse handle(HttpServletRequest req, HandlerMethod method, Exception ex) {
        if (ex instanceof BusinessException) {
            BusinessException exception = (BusinessException) ex;
            log.warn(String.format("访问 %s -> %s 出现业务异常！", req.getRequestURI(), method.toString()), ex);
            return new APIResponse(false, null, exception.getCode(), exception.getMessage());
        } else {
            log.error(String.format("访问 %s -> %s 出现系统异常！", req.getRequestURI(), method.toString()), ex);
            return new APIResponse(false, null, GENERIC_SERVER_ERROR_CODE, GENERIC_SERVER_ERROR_MESSAGE);
        }
    }
}
~~~

出现运行时系统异常后,异常处理程序会直接把异常转换为JSON返回给调用方

## 2.捕获异常后直接生吞

通常情况下,生吞异常的原因,可能是不希望自己的方法抛出受检异常,只是为了把异常处理掉而捕获并生吞异常,也可能是想当然地认为异常并不重要或不可能产生.但不管是什么原因,都不应该生吞,哪怕一个日志也好.

## 3.丢失异常的原始信息

~~~java
private void readFile() throws IOException {
  Files.readAllLines(Paths.get("a_file"));
}
~~~

~~~java
@GetMapping("wrong1")
public void wrong1(){
    try {
        readFile();
    } catch (IOException e) {
        //原始异常信息丢失  
        throw new RuntimeException("系统忙请稍后再试");
    }
}
~~~

上面像这样调用readFile方法,捕获异常后,完全不记录原始异常,直接抛出一个转换后异常,导致出了问题不知道IOException具体是哪里引起的;

~~~java
catch (IOException e) {
    //只保留了异常消息，栈没有记录
    log.error("文件读取错误, {}", e.getMessage());
    throw new RuntimeException("系统忙请稍后再试");
}
~~~

上面这样只记录了异常消息,缺丢失了异常的类型,栈等重要信息,看日志的话也会一年茫然,只知道文件读取错误的文件名,至于为什么读取错误,是不存在还是没权限,完全不知道;

***

这两种处理方式都不太合理,可以改为:

~~~java
catch (IOException e) {
    log.error("文件读取错误", e);
    throw new RuntimeException("系统忙请稍后再试");
}
~~~

~~~java
catch (IOException e) {
    throw new RuntimeException("系统忙请稍后再试", e);
}
~~~

## 4.抛出异常时不指定任何消息

~~~java
throw new RuntimeException();
~~~

这样的异常被ExceptionHandler拦截之后输出的日志信息是:

~~~shell
java.lang.RuntimeException:null
~~~

这里的null非常容易引起误解,容易以为是空指针问题;

 

